### ISSUE TITLE
Failing to reproduce paper results

### ISSUE THREAD

**Issue by palette-knife25** [morningmoni/EDE#1]
Hello!

I have read the paper "Extract, Denoise and Enforce: Evaluating and Improving Concept Preservation for Text-to-Text Generation" and was really interested by it. I have tried to recreate the results on for the Question Generation on SQuAD dataset, but failed. My Rouge-L score for DBA is 13.4818 and for DDBA is 9.5297. Clearly I've done something dramatically wrong and I would appreciate your help. Here are all the steps I've done:

1. I've downloaded SQuAD dataset [here](https://rajpurkar.github.io/SQuAD-explorer/). Then I've separated source input ant target output into train/val/test.source/target files. The _train file_ contains the whole training set. The _val_ and _test_ files are identical and contain dev set from the SQuAD website. The examples can be found [here](https://www.dropbox.com/sh/ysgtcjo7n7eu40g/AABDt5RsFSCiaAKFtWwrbhOwa?dl=0).
2. I've run `python finetune.py`. I did not modify `finetune.py` or `conf.py`. The code completed successfully and saved all the checkpoints.
3. To test the pipeline I've started with using simple spacy-generated constraints. In the paper they are referred as "gold constraints". I have used `en_core_web_sm` spacy model to extract entities referring to the [example](https://spacy.io/usage/linguistic-features#named-entities) here. The results were placed in a `constraint_kpe_em.json` file. You can check it [here](https://www.dropbox.com/sh/ysgtcjo7n7eu40g/AABDt5RsFSCiaAKFtWwrbhOwa?dl=0).
4. Finally, for the evaluation I've run `python run_eval.py` and `python run_eval.py --partial True` to get DBA and DDBA scores, respectively. I did not change anything in the `run_eval.py` file. The scores came out low and were already mentioned above.

I am now working on Automatic constraint generation and trying to apply [this repo](https://github.com/thunlp/BERT-KPE) to SQuAD dataset. Am I correct, that in your repo you are using this [code](https://github.com/morningmoni/EDE/blob/4f30072a656f5f9674403591f1740fbe3a3fca0b/CAS/src/prepro/entity_masking.py) to create constraints? Yet I couldn't figure out how to apply it on SQuAD, though.

However, given the low scores, I have a feeling that there's also something that I could do wrong in the steps described above. Maybe, in the paper some special hyperparameters (different from default ones) were used for the Question Generation task? Could you please help me figure out what's wrong or suggest what steps to take in order to get better scores?

**Comment by morningmoni** [comment]
Hi,

Some quick checks:
1. What's the performance without using any constraint (did you reproduce the BART results)?

2. You should use the following script for evaluation to be consistent with prior studies on SQuAD.
https://github.com/xinyadu/nqg/tree/master/qgevalcap

3. I checked your examples in 1. You need to add the answer as input in addition to the paragraph, so that the model can generate different questions given the same paragraph.

**Comment by palette-knife25** [comment]
Hi,

Thank you for pointing out the mistake in my train/val/test files. I've retrained the model on new files. The `finetune.py` file has produced the `metrics.json` file which says that `test_avg_rougeL: 45.12057724952712`, which is somewhat close to the number reported for BART results.

About p.2, in your code there're some evaluation metrics (including Rouge-L) that are calculated during training and immediately after. For now Rouge-L is enough for me. Is your Rouge-L significantly different from the one in https://github.com/xinyadu/nqg/tree/master/qgevalcap?

Now, I still have problems during inference. I've tried doing it without DBA/DDBA using `python run_eval.py  --use_DBA False`, no other arguments, no modifications to `run_eval.py`. It has produced `test_score.run0.json` file with very low scores: `'rouge1': 16.6526, 'rouge2': 5.2628, 'rougeL': 14.7221, 'rougeLsum': 14.7185}`.
When I execute `python run_eval.py`, the scores are very low, too: `'rouge1': 16.6622, 'rouge2': 5.2573, 'rougeL': 14.7043, 'rougeLsum': 14.719}`. Do you have any idea why this happens?

**Comment by morningmoni** [comment]
Hi,

Can you check if you have used the same hyperparameters as those in training? For example, if you trained the model with use_copy=True, you should use_copy=True in run_eval.py as well. Also check num_beams and max_tgt_length.

ROUGE-L itself is not that different from the one in https://github.com/xinyadu/nqg/tree/master/qgevalcap. But its evaluation strategy is different (not evaluating every example, but one for each paragraph, if I remember correctly)

**Comment by palette-knife25** [comment]
Hello,

Thank you so much for pointing out my mistake! Indeed, I forgot to set use_copy=True in run_eval.py. After that the output became sensible. The ROUGE-L score I've got is slightly lower than the one reported in the paper.

Now I saw another strange issue. I generated an output using this `run_eval.py --use_copy True --use_DBA True`. The full generated file (test.pred.run0.dba) and the constraints file (constraint_kpe_em.json) can be hound [here](https://www.dropbox.com/sh/ysgtcjo7n7eu40g/AABDt5RsFSCiaAKFtWwrbhOwa?dl=0). Here is an example:

- the test source is a passage about Normans (too long to paste here),
- target is "In what country is Normandy located?",
- the constraint generated using spacy is "Normandy",
- the generated output is: "In what country did the Normans give their name to **theirNormandy** region?".

The constraint is in the sentence, however, appears to be glued to the previous word. And this pattern repeats in every sentence, where the constraint word is not in the beginning of the sentence:

- Constraint: "Frankish". Generated sentence: "What does the Old Norse word **forFrankish** word "Norseman" mean?"
- Constraint: "Christian". Generated sentence: "Whose contingents raided and ultimately settled Normandy and parts of **theChristian** coast?"

I've checked the generation process and I think I've found the reason for this error. I will explain on the first example with Normandy. The tokenized version of a constraint is produced at this [line](https://github.com/morningmoni/EDE/blob/b057859c6be8c227d402c7cfccd6b0d53b728274/run_eval.py#L77). For "Normandy" it will be `[[46333, 10708]]`. Then, the [model.generate(...)](https://github.com/morningmoni/EDE/blob/b057859c6be8c227d402c7cfccd6b0d53b728274/run_eval.py#L86) produces this sequence: `[2, 0, 1121, 99, 247, 222, 5, 20336, 1253, 492, 49, 766, 7, 49, 46333, 10708, 976, 116, 2, 1]`, which is decoded into "In what country did the Normans give their name to **theirNormandy** region?". Now, using `tokenizer.batch_decode(ids, skip_special_tokens=True, clean_up_tokenization_spaces=True)`, I've compared ids to the tokens and got that:

2 ''
0 ''
1121 'In'
99 ' what'
247 ' country'
222 ' did'
5 ' the'
20336 ' Norm'
1253 'ans'
492 ' give'
49 ' their'
766 ' name'
7 ' to'
49 ' their'
**46333 'Norm'
10708 'andy'**
976 ' region'
116 '?'
2 ''
1 ''

All corresponding tokens are with spaces, while 46333 'Norm' is without one. I believe that this is because the constraint "Normandy" was tokenized as `[[46333, 10708]]` and the id 46333 was enforced, while id for ' Norm' (with space) is different: 20336. That is why "their" and "Normandy" were glued together. I could've just insert the space in required position before writing into file, but I think that this error has an affect on the quality of generated output (why enforcing 46333 when 20336 could be a fit, too). Did you have this issue? Maybe you have an idea where this could come from?

**Comment by morningmoni** [comment]
Hi,

You are right about inserting a space before the word as the constraint (we did the same too). This is due to the tokenization of BART -- you don't have to worry about it if you use a pre-trained language model that doesn't include space in the vocabulary.

**Comment by palette-knife25** [comment]
Hello,

Indeed, adding a leading space to constraints resolved the issue. Everything is working correctly and I've finally got the results I needed. Thank you so much for all your help!
